version: "3.7"
services:
  app:
    build:
      args:
        user: 99diagha
        uid: 1000
      context: ./
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - net
  mysql:
    image: mysql:8
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - net
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - net
networks:
  net:
    driver: bridge
volumes:
  mysql:
    driver: local
